version: '3.9'

services:
  db:
    image: postgres:16
    container_name: wallet_db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: walletpass
    ports:
      - "15432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - walletnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: wallet_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: wallet
      RABBITMQ_DEFAULT_PASS: walletpass
    ports:
      - "15672:15672"     # AMQP
      - "5673:5672"   # Management UI
    networks:
      - walletnet

  app:
    build: .
    container_name: wallet_app
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/walletdb
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: walletpass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: wallet
      SPRING_RABBITMQ_PASSWORD: walletpass
    ports:
      - "9191:9191"
    networks:
      - walletnet

volumes:
  dbdata:

networks:
  walletnet:
    driver: bridge
