server:
  port: 9191
  servlet:
    context-path: /api/v1

spring:
  application:
    name: wallet-service

wallet:
  services:
    crb:
      cost: 50.00
      enabled: true
    kyc:
      cost: 25.00
      enabled: true
    credit-scoring:
      cost: 75.00
      enabled: true
  queue:
    transaction-queue: wallet.transactions
    dlq-queue: wallet.transactions.dlq
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,rabbitmq
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.wallet: DEBUG
    org.springframework.web: INFO
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ---------------------------
# DEV PROFILE
# ---------------------------
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:walletdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: wallet
    password: walletpass
    virtual-host: /
    template:
      enabled: false

# ---------------------------
# TEST PROFILE
# ---------------------------
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: wallet
    password: walletpass
    virtual-host: /
    template:
      enabled: false

# ---------------------------
# PROD PROFILE
# ---------------------------
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://db:5432/walletdb
    username: wallet
    password: walletpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: wallet
    password: walletpass
    virtual-host: /
